### ISSUE TITLE
Hanna and Rails 3

### ISSUE THREAD

**Issue by gdeest** [mislav/hanna#19]
Hi,

I had a very hard time of making Hanna work with Rails 3 (pre). It looks like all is required is to append the following line to Gemfile:

gem "hanna", '0.1.12', :require => 'hanna/rdoctask'

Perhaps it would help others to update the instructions.

Hope this helps !

**Comment by nasa42** [comment]
Yes, it helped me.
Adding <code>gem 'hanna', :require => 'hanna/rdoctask'</code> in <code>Gemfile</code> helped me suppressing following error - 

<code>
/usr/lib/ruby/gems/1.8/gems/rdoc-2.3.0/lib/rdoc/generator/html.rb:44: uninitialized constant RDoc::RDoc (NameError)
    from /usr/lib/ruby/gems/1.8/gems/hanna-0.1.12/lib/hanna/hanna.rb:9:in `require'
    from /usr/lib/ruby/gems/1.8/gems/hanna-0.1.12/lib/hanna/hanna.rb:9
    from /usr/lib/ruby/gems/1.8/gems/hanna-0.1.12/lib/hanna.rb:1:in`require'
    from /usr/lib/ruby/gems/1.8/gems/hanna-0.1.12/lib/hanna.rb:1
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:64:in `require'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:64:in`require'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:62:in `each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:62:in`require'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:51:in `each'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler/runtime.rb:51:in`require'
    from /usr/lib/ruby/gems/1.8/gems/bundler-1.0.0.rc.5/lib/bundler.rb:107:in `require'
    from [....absolute path to application here....]/config/application.rb:3
    from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0.rc/lib/rails/commands.rb:21:in`require'
    from /usr/lib/ruby/gems/1.8/gems/railties-3.0.0.rc/lib/rails/commands.rb:21
    from script/rails:6:in `require'
    from script/rails:6
</code>

Thanks.

**Comment by raggi** [comment]
At runtime, you probably don't want to require anything, I'd recommend having `:require => nil`
